feat(android): add serial number support for zebra devices on android…
MobisysGmbH/cordova-plugin-device pull request #1
Opened 2022-01-07 09:44 UTC by alexander-gruenewald

This is a fork of the oficial [cordova-plugin-device](https://github.com/apache/cordova-plugin-device) adding the possibility to read out the serial number of a zebra device running on Android 10 or higher by using [DeviceIdentifiersWrapper](https://github.com/ZebraDevs/DeviceIdentifiersWrapper).

2022-01-18 12:59 UTC, robin-hartmann requested changes

2022-01-18 12:59 UTC, robin-hartmann commented on README.md
> +## Info
Should be reworded to "Notice", because "Info" is very generic.

```suggestion
## Notice
```

2022-01-18 12:59 UTC, robin-hartmann commented on README.md
> +This is a fork of the oficial [cordova-plugin-device](https://github.com/apache/cordova-plugin-device) adding the possibility to read out the serial number of a zebra device running on Android 10 or
```suggestion

This is a fork of the official [cordova-plugin-device](https://github.com/apache/cordova-plugin-device) with the goal to add the possibility to read the serial number of Zebra devices running on Android 10 or higher by using Zebra's [DeviceIdentifiersWrapper](https://github.com/ZebraDevs/DeviceIdentifiersWrapper).
```

2022-01-18 12:59 UTC, robin-hartmann commented on README.md
> +# cordova-plugin-device (with zebra s/n support on Android 10+)
This plugin, the generated npm package and this repository should be renamed to `mobisys-cordova-plugin-device`. Also, there's no need to mention the feature in the title - the title should only contain the project name.

```suggestion
# mobisys-cordova-plugin-device
```

2022-01-18 12:59 UTC, robin-hartmann commented on plugin.xml
> +        <framework src="com.github.ltrudu:DeviceIdentifiersWrapper:0.2" />
Please move `framework` above `config-file` and add an empty line after it. The order should be `dependency`, `framework`, `podspec`, `config-file` then `source-file`/`header-file`, so dependencies come first and source files come last.

2022-01-18 12:59 UTC, robin-hartmann commented on src/android/Device.java
> +    private JSONObject _returnValue = new JSONObject();
Do not keep these as state as this can cause issues with multiple threads. Instead, these should be passed around as parameters when required.

2022-01-18 12:59 UTC, robin-hartmann commented on src/android/Device.java
> +        return false;
Can be simplified:

```suggestion
        return android.os.Build.MANUFACTURER.toLowerCase().startsWith(ZEBRA_DEVICE);
```

2022-01-18 12:59 UTC, robin-hartmann commented on src/android/Device.java
> +     */
```suggestion
    /**
     * Checks if this device is manufactured by Zebra.
     *
     * @return True if this device is manufactured by Zebra, false if not.
     */
```

2022-01-18 12:59 UTC, robin-hartmann commented on src/android/Device.java
> +     */
```suggestion
    /**
     * Tries to retrieve the serial number of a Zebra device using DeviceIdentifiersWrapper.
     *
     * For more information see:
     * https://github.com/ZebraDevs/DeviceIdentifiersWrapper
     */
```

2022-01-18 12:59 UTC, robin-hartmann commented on src/android/Device.java
> +                Log.i("triggerZebraSNRetrieval", message);
Should use log level debug, as this is obviously debug information.

```suggestion
                Log.d(TAG, "Zebra serial number retrieval debug status: " + message);
```

2022-01-18 12:59 UTC, robin-hartmann commented on src/android/Device.java
> +            addToReturnValue("isVirtual", this.isVirtual());
To me it seems that there's no need for an additional function `addToReturnValue` (at least once `_callbackContext` and `_returnValue` are moved to parameters).

2022-01-18 12:59 UTC, robin-hartmann commented on src/android/Device.java
> +
Please move the entire `if` block (except `return true`) into a separate function `getDeviceInfo` and pass `callbackContext` as parameter.

2022-01-18 12:59 UTC, robin-hartmann commented on src/android/Device.java
> +    }
Should be removed.

2022-01-18 12:59 UTC, robin-hartmann commented on src/android/Device.java
> +                Log.e("triggerZebraSNRetrieval", message);
The first parameter should be a tag unique to this module. I'd recommend adding a member variable for this purpose:

```java
private static final String TAG = Device.class.getCanonicalName();
``` 

Also, you should add more context to the message:

```suggestion
                Log.e(TAG, "error while retrieving Zebra serial number: " + message);
```

2022-01-18 12:59 UTC, robin-hartmann commented on src/android/Device.java
> +                this.triggerZebraSNRetrieval(this.cordova.getContext());
```suggestion
                this.retrieveZebraSerialNumber(this.cordova.getContext());
```

2022-01-18 16:14 UTC, alexander-gruenewald commented
thanks for your thorough review and your comments
I applied all of your suggestions - please have another look

2022-01-19 12:33 UTC, robin-hartmann requested changes

2022-01-19 12:33 UTC, robin-hartmann commented on plugin.xml
> +        <framework src="build-extras.gradle" custom="true" type="gradleReference" />
Please move the `build-extras.gradle` file into `src/android`, as this is only relevant for Android.

2022-01-19 12:33 UTC, robin-hartmann commented on src/android/Device.java
> +     * @return
Remove `@return`, as this is a `void` function.

```suggestion
```

2022-01-19 12:33 UTC, robin-hartmann commented on src/android/Device.java
> +                    Log.i(TAG, e.getMessage());
Should be log level error and should include information about context:

```suggestion
                    Log.e(TAG, "error while assigning serial number to JSONObject: " + e.getMessage());
```

2022-01-19 13:13 UTC, robin-hartmann approved these changes

2022-01-20 05:13 UTC, merged